Enable location sharing
tchapgouv/tchap-android pull request #1020
Opened 2024-03-25 22:33 UTC by yostyle

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

## Screenshots / GIFs

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt)

2024-03-26 10:38 UTC, NicolasBuquet requested changes
Remarque générale de tagguer avec // Tchap: les modifs pour faciliter les futurs rebase.

2024-03-26 10:38 UTC, NicolasBuquet commented on vector-config/src/main/java/im/vector/app/config/Config.kt
Si on est synchro avec le code Element, enlever le commentaire Tchap.

2024-03-26 10:38 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
Mettre des commentaire // Tchqp: pour tagguer les adaptations par rapport à Element pour les futurs rebase.

2024-03-28 10:44 UTC, NicolasBuquet requested changes

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
> +    lateinit var mapRenderer: MapRenderer
Add Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
> -            GlideApp.with(holder.staticMapImageView)
Laisser ces lignes en commentaire pour faciliter les futurs rebase ?

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
> +        mapRenderer.clear(holder.staticMapImageView, holder.staticMapPinImageView)
Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> +        private val mapRenderer: MapRenderer,
Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> +//        private val urlMapProvider: UrlMapProvider,
Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> +            mapRenderer(host.mapRenderer)
Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> -                locationUrl = locationUrl,
Laisser la ligne en commnetaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
> +        private val mapRenderer: MapRenderer,
Ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
> -        val width = timelineMediaSizeProvider.getMaxSize().first
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
> -                .locationUrl(locationUrl)
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> +        private val mapRenderer: MapRenderer,
Ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> + //       private val urlMapProvider: UrlMapProvider,
Ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> -        val width = timelineMediaSizeProvider.getMaxSize().first
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> -                .locationUrl(locationUrl)
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -    var locationUrl: String? = null
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -    var mapWidth: Int = 0
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -    var mapHeight: Int = 0
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> +    override fun unbind(holder: H) {
Ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -        val location = locationUrl ?: return
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -            width = mapWidth
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -        GlideApp.with(holder.staticMapImageView)
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -                        holder.staticMapPinImageView.setImageDrawable(null)
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -                })
Laisser les lignes en commentaire et ajouter un Tchap comment

2024-03-28 10:44 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/location/MapRenderer.kt
> +class MapRenderer @Inject constructor() {
Appeler la classe TchapMapRenderer ?

2024-03-28 12:07 UTC, yostyle commented on vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
> -            GlideApp.with(holder.staticMapImageView)
on aura l'historique git et le code est déplacé dans map renderer.

2024-03-28 12:30 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> -
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:30 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
> -                locationUrl = locationUrl,
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:30 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
> -        val width = timelineMediaSizeProvider.getMaxSize().first
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:37 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
> -                .locationUrl(locationUrl)
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:39 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> -        val width = timelineMediaSizeProvider.getMaxSize().first
ajout d'un commentaire

2024-03-28 12:42 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
> -                .locationUrl(locationUrl)
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:42 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -    var locationUrl: String? = null
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:44 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -        val location = locationUrl ?: return
Il s'agit d'une modification du fonctionnement d'une feature existente et non pas une désactivation de celle-ci. L'historique git est suffisant.

2024-03-28 12:45 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -                        holder.staticMapPinImageView.setImageDrawable(null)
le code a été déplacé et non supprimé

2024-03-28 12:46 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -                })
le code a été déplacé et non supprimé

2024-03-28 12:46 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/location/MapRenderer.kt
> +class MapRenderer @Inject constructor() {
J'ai hésité en effet. je vais la renommer.

2024-03-28 13:01 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
> -        GlideApp.with(holder.staticMapImageView)
La code a été déplacé dans le renderer et n'a pas été supprimé

2024-03-28 15:53 UTC, NicolasBuquet approved these changes
LGTM

2024-03-28 16:11 UTC, merged