Yostyle/fix image permission
tchapgouv/tchap-android pull request #1022
Opened 2024-04-08 19:40 UTC by yostyle

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

## Screenshots / GIFs

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/tchapgouv/tchap-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt)

2024-04-09 15:30 UTC, NicolasBuquet requested changes
Mutualiser la configuration de l'appel `getSelectedUriList`

2024-04-09 15:30 UTC, NicolasBuquet commented on library/multipicker/src/main/java/im/vector/lib/multipicker/AudioPicker.kt
> +            context.grantUriPermission(context.applicationContext.packageName, selectedUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
Pourrais être mutualisé dans la classe parente multipicker/Picker::getSelectedUriList

2024-04-09 15:30 UTC, NicolasBuquet commented on library/multipicker/src/main/java/im/vector/lib/multipicker/FilePicker.kt
> +            context.grantUriPermission(context.applicationContext.packageName, selectedUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
Pourrais être mutualisé dans la classe parente multipicker/Picker::getSelectedUriList

2024-04-09 15:30 UTC, NicolasBuquet commented on library/multipicker/src/main/java/im/vector/lib/multipicker/ImagePicker.kt
> +            context.grantUriPermission(context.applicationContext.packageName, selectedUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
Pourrais être mutualisé dans la classe parente multipicker/Picker::getSelectedUriList

2024-04-09 15:30 UTC, NicolasBuquet commented on library/multipicker/src/main/java/im/vector/lib/multipicker/MediaPicker.kt
> +            context.grantUriPermission(context.applicationContext.packageName, selectedUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
Pourrais être mutualisé dans la classe parente multipicker/Picker::getSelectedUriList

2024-04-09 15:30 UTC, NicolasBuquet commented on library/multipicker/src/main/java/im/vector/lib/multipicker/VideoPicker.kt
> +            context.grantUriPermission(context.applicationContext.packageName, selectedUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
Pourrais être mutualisé dans la classe parente multipicker/Picker::getSelectedUriList

2024-04-09 15:30 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
> +    data class CancelSend(val event: TimelineEvent, val force: Boolean) : RoomDetailAction()
Ajouter un Tchap commentaire

2024-04-09 15:30 UTC, NicolasBuquet commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt
> +    data class Cancel(val event: TimelineEvent, val force: Boolean) :
Add Tchap commentaire

2024-04-09 15:32 UTC, NicolasBuquet reviewed
Ajouter un changelog STP

2024-04-10 00:48 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
> +    data class CancelSend(val event: TimelineEvent, val force: Boolean) : RoomDetailAction()
je préfère ne pas en mettre. le lint oblige d'ajouter un saut de ligne au dessus du commentaire. ca rajoute de la complexité inutile en cas de conflit.

2024-04-10 00:48 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt
> +    data class Cancel(val event: TimelineEvent, val force: Boolean) :
je préfère ne pas en mettre. le lint oblige d'ajouter un saut de ligne au dessus du commentaire. ca rajoute de la complexité inutile en cas de conflit.

2024-04-10 09:20 UTC, NicolasBuquet approved these changes
PR assez conséquente ! Bravo 👏 

LGTM

2024-04-10 10:09 UTC, merged