Add New Targets to build
tchapgouv/tchap-android pull request #653
Opened 2022-06-27 23:53 UTC by jdauphant

## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Content

Add new target to automatically build

## Motivation and context

I need dev APKs for testing purpose.
I want to test VoIP to

2022-06-27 23:54 UTC, jdauphant commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning
:thinking: I may need to pull that in debug in fact

2022-06-28 16:07 UTC, jdauphant commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning
Let's do that

2022-07-12 12:27 UTC, Florian14 commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning
```suggestion
        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning, FdroidDevTchapWithoutvoipWithoutpinning, GplayBtchapWithvoipWithpinning ]
```

2022-07-12 12:30 UTC, Florian14 approved these changes
LGTM but that will increase the CI duration and the risk of failure while generating the apks (there are 4 APKs for each variant)

2022-07-12 14:19 UTC, yostyle commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning
DevTchap should not be used on main branch
```suggestion
        target: [ GplayBtchapWithoutvoipWithpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning, GplayBtchapWithvoipWithpinning ]
```

2022-07-12 14:58 UTC, yostyle requested changes
DevTchap should be used to debug instead of Btchap except to test VoIP and pinning.

2022-07-12 23:04 UTC, jdauphant commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, GplayDevTchapWithoutvoipWithpinning, FdroidDevTchapWithoutvoipWithoutpinning, GplayBtchapWithvoipWithpinnin
Good for me

2022-07-12 23:05 UTC, jdauphant commented on .github/workflows/build.yml
> +        target: [ GplayDevTchapWithoutvoipWithoutpinning, FdroidDevTchapWithoutvoipWithoutpinning, GplayBtchapWithvoipWithpinning ]
@yostyle :
```suggestion
        target: [ GplayDevTchapWithoutvoipWithoutpinning, FdroidDevTchapWithoutvoipWithoutpinning ]
```

2022-07-27 06:54 UTC, yostyle approved these changes

2022-07-27 06:55 UTC, merged