Add service status url
tchapgouv/tchap-android pull request #961
Opened 2023-09-04 21:04 UTC by yostyle

#955

2023-09-05 19:43 UTC, NicolasBuquet commented
Le message d'erreur ne doit pas apparaître quand l'appareil n'a plus de connexion (sinon l'appareil aura de toute façon du mal à atteindre la page web de statut des serveur s'il n'a pas de connexion).
En fait, ce message doit plutôt apparaître quand le home server retourne une erreur 500 (qui peut être déclenchée entre autres à cause d'un timeout, surcharge serveur…)

2023-09-05 19:44 UTC, NicolasBuquet requested changes
Le message d'erreur ne doit pas apparaître quand l'appareil n'a plus de connexion (sinon l'appareil aura de toute façon du mal à atteindre la page web de statut des serveur s'il n'a pas de connexion).
En fait, ce message doit plutôt apparaître quand le home server retourne une erreur 500 (qui peut être déclenchée entre autres à cause d'un timeout, surcharge serveur…)

2023-09-05 19:53 UTC, yostyle commented
> Le message d'erreur ne doit pas apparaître quand l'appareil n'a plus de connexion (sinon l'appareil aura de toute façon du mal à atteindre la page web de statut des serveur s'il n'a pas de connexion). En fait, ce message doit plutôt apparaître quand le home server retourne une erreur 500 (qui peut être déclenchée entre autres à cause d'un timeout, surcharge serveur…)

Sur Android l'état "no connection" est utilisé quand le serveur est inaccessible peu importe la cause. Sur le web ce message s'affiche quand il y'a une perte de connexion avec le serveur.

2023-09-06 10:48 UTC, NicolasBuquet approved these changes
On pourrait améliorer la mise en place des attributs de lien en repérant l'emplacement de `statusLink` dans le spannable. Cela éviterait de considérer qu'il est forcément à la fin.

2023-09-07 19:20 UTC, merged